- otel_observer.c
- tests/function_closure.phpt
- tests/function_first_class_callable.phpt
> Resolve observer for closures

- .github/workflows/build.yml
- README.md
Build and test the extension on PR and merge to main.
> adding build/test workflow

- otel_observer.c
- tests/multiple_hooks_modify_params.phpt
Fixing propagation of parameter modifications by multiple hooks
> fix: propagate multiple hooks params modifications

- otel_observer.c
- tests/function_internal.phpt
PHP 8.2 includes internal function in the observer API https://github.com/php/php-src/commit/625f1649639c2b9a9d76e4d42f88c264ddb8447d.
> Allow hooking internal functions

- DEVELOPMENT.md
Initial description of extension debugging process
> docs: adding description of debugging process

- bin/install.php
Getting rid of hardcoded auto packages array and get them through packagist api
> get list of auto packages through packagist api

- .clang-format
- README.md
- opentelemetry.c
- opentelemetry_arginfo.h
- otel_observer.c
- otel_observer.h
- php_opentelemetry.h
adding .clang-format and format source files based on it
> Consistent source code formatting 

- otel_observer.c
- tests/calling_die_lead_to_segfault.phpt
Fixes https://github.com/open-telemetry/opentelemetry-php/issues/951
> calling die or exit directly lead to segfault

- .github/workflows/check-style.yml
- docker/Dockerfile.debian
adding clang-format github action, and as a debian dependency for local dev
> clang-format

- ext/tests/expand_arguments.phpt
> add failing test for expand params with post callback

- DEVELOPMENT.md
- docker-compose.yaml
- docker/Dockerfile.debian
adding valgrind to debian image, and instructions on how to run it to check for memory leaks
> adding valgrind

- docker/Dockerfile.debian
fix clang-format installation, and minor tidy of dockerfile
> fixing clang-format install

- .github/workflows/build.yml
- DEVELOPMENT.md
- README.md
- ext/otel_observer.c
- ext/tests/modify_named_params.phpt
- ext/tests/modify_params.phpt
- ext/tests/multiple_hooks_modify_returnvalue.phpt
* Fixing a crash bug if you use string array key in pre hook callback.
* document how pre functions can modify params
* document how post function can modify return value
* simplify multiple post hooks test
> fixing crash + docs

- ext/format.sh
- ext/otel_observer.c
- ext/tests/expand_params_internal.phpt
- ext/tests/post_hook_return_ignored_without_type.phpt
- ext/tests/return_expanded_params.phpt
- ext/tests/return_expanded_params_internal.phpt
- ext/tests/return_reduced_params.phpt
adding tests to confirm some behaviour, and xfail tests for failure cases
> adding more tests

- .github/workflows/build.yml
- README.md
* build for windows
* add a short doc point linking to Windows build instructions
* rename linux build
> adding windows build action

- .github/workflows/publish-php-debug-images.yml
- docker-compose.yaml
adds 8.3 local builds, and also github build of our debug/dev image
> adding php 8.3 dev image

- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/publish-php-debug-images.yml
- Makefile
Pending a merge and release of https://github.com/cmb69/setup-php-sdk/pull/22
> Include PHP 8.3 in build matrix

- ext/otel_observer.c
- ext/package.xml
- ext/tests/modify_named_params_internal.phpt
- ext/tests/modify_named_params_invalid.phpt
- ext/tests/modify_named_params_twice.phpt
Resolves https://github.com/open-telemetry/opentelemetry-php/issues/1153
Found a private function for mapping name to index in PHP sources, so reusing that. The rest is quite straightforward.
Added some additional test cases for various corner cases (named arg does not exist, modifying via index and name both).
> Support modifying named params

- README.md
Closes: https://github.com/open-telemetry/opentelemetry-php/issues/1278
> document hook race conditions

- ext/otel_observer.c
> Fix int-bool usage for s390x

- README.md
Related to https://github.com/open-telemetry/community/issues/2830
> Standardize section listing maintainer, approver, etc

- ext/otel_observer.c
- ext/tests/unwind_exit_leak.phpt
- ext/tests/unwind_exit_pcntl_async_signal.phpt
- ext/tests/unwind_exit_pcntl_async_signal_leak.phpt
Fixes https://cloud-native.slack.com/archives/C01NFPCV44V/p1751529276287599?thread_ts=1751529276.287599&cid=C01NFPCV44V
> Do not suppress unwind exception in `exception_isolation_end`
