open-telemetry/opentelemetry-php-instrumentation

otel_observer.c
Testing it on PHP-8.2. In debug mode it results in following assertion `Assertion failed: (zval_gc_type((ref)->gc.u.type_info) == 7 || zval_gc_type((ref)->gc.u.type_info) == 8), function gc_possible_root, file zend_gc.c, line 647`
`PASS Check if otel_instrumentation is loaded [tests/001.phpt] `
`PASS Check if hook returns true [tests/002.phpt] `
`FAIL Check if hooks are invoked [tests/003.phpt] `
`FAIL Check if multiple hooks are invoked [tests/004.phpt] `
`FAIL Check if hooks receives function information [tests/005.phpt] `
`FAIL Check if hooks receives arguments and return value [tests/006.phpt] `
`FAIL Check if hook receives exception [tests/007.phpt] `
`FAIL Check if hook can modify arguments [tests/008.phpt] `
`FAIL Check if hook can modify not provided arguments [tests/009.phpt] ` …
=> fix: most tests are failing (crashing) due to lack of refcount increase

otel_instrumentation.c, otel_observer.c
`PHP_RSHUTDOWN_FUNCTION` should return `zend_result`.
`add_observer` returns bool, not int, so use true and false instead of 1 and true.
=> Fix minor issues with returns

README.md, otel_observer.c, tests/multiple_hooks_modify_returnvalue.phpt
Without additional echo call in helloWorld, code for main looks as follows 
`$_main:
; (lines=4, args=0, vars=0, tmps=1)
; (after optimizer)
; /Users/pdelewski/Projects/php-auto/test3.php:1-8
0000 INIT_FCALL 1 112 string("var_dump")
0001 SEND_VAL int(1) 1
0002 DO_ICALL
0003 RETURN int(1)`
which means that call to helloWorld has been optimized out and in result hooks are not invoked
=> fix: propagate return value modifications

otel_observer.c
All tests are passing now on debug build without memory problems
```
=====================================================================
PHP         : /Users/pdelewski/php-bin/DEBUG/bin/php 
PHP_SAPI    : cli
PHP_VERSION : 8.2.0-dev
ZEND_VERSION: 4.2.0-dev
=====================================================================
TIME START 2022-11-24 11:27:20
=====================================================================
PASS Check if otel_instrumentation is loaded [tests/001.phpt] 
PASS Check if hook returns true [tests/002.phpt] 
PASS Check if hooks are invoked [tests/003.phpt] 
PASS Check if multiple hooks are invoked [tests/004.phpt] 
PASS Check if hooks receives function information [tests/005.phpt] 
PASS Check if hooks receives arguments and return value [tests/006.phpt] 
PASS …
```
=> fix: throwing new exception from post hook lead to memory leak

bin/install.php
Since 1.15 php-http/discovery requires `allow-plugins` setting. Set it to false by default
=> deny plugins for php-http/discovery by default

bin/install.php
Adding `--non-interactive` to require command to prevent hanging and waiting for user interaction
=> execute composer require in non-interactive mode

README.md
Fixes https://github.com/open-telemetry/opentelemetry-php-instrumentation/issues/41
Maybe better would be prepare fully working example and do some improvements in https://github.com/open-telemetry/opentelemetry-php/blob/main/src/Context/DebugScope.php?
=> store scope in the context

otel_observer.c, tests/unwind_exit.phpt
Do not pass UnwindExit to post observer callback
Related: https://github.com/open-telemetry/opentelemetry-php/issues/951
=> handle UnwindExit

ext/otel_observer.c, ext/tests/return_params.phpt, ext/tests/return_params_internal.phpt
when the original $params array is returned (with or without modification), we do not need any extra processing to replace the original parameters - that is already taken care of.
=> fixing segfault when returning params from pre callback

ext/otel_observer.c, ext/tests/expand_params_internal.phpt
when debugging issue 68 (expand params of internal function causes segfault), I gained more understanding of what's going on, but no solution yet. Documenting my findings in the .phpt test.
Also, small refactor/tidy of some of the code based on my testing. Replace refcount check with macro, per https://www.phpinternalsbook.com/php7/zvals/memory_management.html
Related: #68
=> adding notes and minor code improvements for issue 68

README.md, ext/opentelemetry.c, ext/tests/disable_does_nothing_with_bad_data.phpt, ext/tests/disabled_with_conflicting_extension.phpt
accept a list of conflicting extensions via .ini. If a conflicting extension is loaded, do not initialize opentelemetry.
=> adding checks for conflicting extensions

.github/workflows/build.yml, README.md, ext/opentelemetry.c, ext/otel_observer.c, ext/php_opentelemetry.h, ext/tests/007.phpt, ext/tests/disable_hook_function_validation.phpt, ext/tests/invalid_post_callback_signature.phpt, ext/tests/invalid_pre_callback_signature.phpt, ext/tests/invalid_pre_callback_signature_with_function.phpt, ext/tests/multiple_hooks_modify_returnvalue.phpt
trying to execute a hook function when the provided callback's signature does not match reality is a fatal error. Check the signature before calling, and if they do not match, do not execute the callback
Fixes: https://github.com/open-telemetry/opentelemetry-php-instrumentation/issues/81
=> check for invalid hook function signatures

docker/Dockerfile.debian, ext/otel_observer.c, ext/tests/expand_params_internal.phpt
expanding arguments for internal functions from a pre callback causes a segfault. until we can fix it properly, disable the behaviour and log to error_log.
also remove some dead/unreachable code, and add gdbserver to the docker image since I've been using it a lot.
=> disabling expanding args for internal functions

ext/config.w32, ext/otel_observer.c, ext/tests/005.phpt, ext/tests/006.phpt, ext/tests/invalid_post_callback_signature.phpt, ext/tests/invalid_pre_callback_signature.phpt, ext/tests/invalid_pre_callback_signature_with_function.phpt
=> For WINDOWS build!

README.md, ext/package.xml, ext/tests/static_method.phpt
it's not documented anywhere what the first param for pre/post callbacks is when hooking a static class method. Adds a test and a note to the readme.
=> adding test and doc for hooking static method

.github/workflows/build.yml, ext/otel_observer.c, ext/tests/expand_params_internal.phpt, ext/tests/invalid_post_callback_signature.phpt, ext/tests/invalid_pre_callback_signature.phpt, ext/tests/invalid_pre_callback_signature_with_function.phpt, ext/tests/return_expanded_params_internal.phpt
Changed segfault method based on issue/enhacement #90 
Tests `expand_params_internal.phpt` and `return_expanded_params_internal.phpt` skipped if PHP < 8.2 because don't allow `null` and `false` as standalone types.
Only PHP 8.2+ allow null and false as standalone types:
https://php.watch/versions/8.2/null-false-types
=> Change segfault method!

ext/otel_observer.c
Resolves #59 and most likely also #80 
I have managed to reproduce the crash in #59 locally on PHP 8.2.10 with a minimal sample (running via Apache).
```php
<?php
function test() {}
header_register_callback('test');
```
This happens because if nothing has been written to output, `php_output_deactivate` causes `sapi_send_headers` to be called, which in turn runs the header callback. Since header callback is a PHP function, the observer callback is invoked for that. The problem is that `php_output_deactivate` was called by `php_request_shutdown` immediately after module RSHUTDOWN callbacks were called, in which `observer_class_lookup` used by our observer callback is freed and set to `NULL`.
I have confirmed that the crash in the above sample stops reproducing after this change. …
=> Fix segfault by checking observer_class_lookup for NULL in observer callback

README.md, ext/opentelemetry.c
a bug has been fixed which means we no longer segfault if the blackfire extension is installed. Remove the conflict, and update readme.
=> re-enable blackfire

.github/workflows/publish-php-debug-images.yml
dont clobber the dockerfile arg for PHP_CONFIG_OPTS, which includes --with-pear. this will allow us to pear package within the build
=> add pear to build

ext/tests/post_hooks_after_die.phpt
test that post hooks still execute after die/exit is called
=> adding test for post hooks after die/exit

.github/workflows/build.yml, .github/workflows/publish-php-debug-images.yml
This automates the publishing of some artifacts:
* windows binaries
* PECL package
Those artifacts are generated on each action run, uploaded and available from the relevant github action.
When a tag is pushed, it will also create a release for that tag, uploading the artifacts to the release page. For this to work, you need to create a tag without a release (which you can't do from github UI, so I've got a separate PR coming for dev-tools which creates a tag).
Closes: #95
=> create draft release on tag, publish windows and pecl builds

README.md
Our existing conflict checking doesn't work with zend extensions, since they're loaded after normal extensions. Moving the checks to later (eg in RINIT) breaks our extension, so the best I think we can do is to just document it.
Closes: #106
=> document SourceGuardian incompatibility

ext/package.xml, ext/tests/post_hook_type_error.phpt
if an invalid typehint is provided for first param of post callback, this would previously cause a hang. fixed by #118, this test confirms the fix works in this scenario.
=> adding test for post hook type error

ext/opentelemetry.c, ext/package.xml, ext/tests/ini_set.phpt
Resolves https://github.com/open-telemetry/opentelemetry-php/issues/1195
Currently INI options are unregistered in `RSHUTDOWN`, which is incorrect and will cause a crash on shutdown if `ini_set` has been used in code. Moved it to `MSHUTDOWN`.
=> Fix crash by unregistering INI in MSHUTDOWN instead of RSHUTDOWN

ext/.gitignore, ext/otel_observer.c, ext/package.xml, ext/tests/expand_params_extra.phpt, ext/tests/expand_params_internal.phpt, ext/tests/modify_extra_params.phpt, ext/tests/modify_extra_params_internal.phpt, ext/tests/return_expanded_params_internal.phpt
Some additional context here: https://github.com/open-telemetry/opentelemetry-php/issues/1155#issuecomment-1905288940
Limited the maximum index of parameters provided by begin hook to below `max(defined_param_count, callsite_param_count)`. Within this limit, the call frame already has all the slots present and the call frame size does not need to be extended. Extension would not possible here because it might require reallocating the call frame to a different location and the current call frame pointer is stored in local variables of functions that called our observer.
Additionally, fixed writing to "extra" parameter slots (parameters that were provided at call site but not part of function definition). Previously, it was assumed that all parameters are stored continuously in memory, but …
=> Fix modifying extra parameters, limit parameter expansion

ext/otel_observer.c
- warning: unused variable '...' [-Wunused-variable]
- warning: format '%u' expects argument of type 'unsigned int', but argument 4 has type 'zend_ulong' {aka 'long unsigned int'} [-Wformat=]
=> Fix build warnings

.gitignore, ext/opentelemetry.c, ext/otel_observer.c, ext/package.xml, ext/tests/expand_params_extra.phpt, ext/tests/expand_params_internal.phpt, ext/tests/hooks_throw_exception_error_handler.phpt, ext/tests/modify_named_params_invalid.phpt, ext/tests/return_expanded_params_internal.phpt
Use `E_CORE_WARNING` error type to prevent PHP function from being executed when calling `php_error_docref` in observer pre/post hook handling. Reasoning is explained below:
Calling `php_error_docref` will call the PHP function provided with `set_error_handler` for most error types. This error handler may throw exceptions, and cause the situation where begin handler finishes with an exception being active. This causes a hang or crash similar to how it happened when exceptions from pre hook itself weren't cleared.
The options to fix this is to either use an error type that cannot call user error handler function, or clear the exception *again* after calling `php_error_docref`. However, it seems that some error handlers actually intentionally throw an exception, so it could be caught by …
=> Fix exception raised by `php_error_docref` that hangs the process in hook

docker/Dockerfile.debian, ext/format.sh
the dev image had broken because clang-format-18 was no longer available. switching to clang-format seems to work, and upgrade to debian bookworm for good measure.
=> fix clang-format installation

ext/package.xml
instead of listing all of the changes in each notes field, just link to the github release
=> simplify package.xml release notes

ext/config.m4
Resolves https://github.com/open-telemetry/opentelemetry-php/issues/1230
Options `-Wall -Wextra` enable almost all known warnings and `-Werror` makes any warning fail the build. `-Wno-unused-parameter` excludes the warning of unused parameters, which cannot be avoided anyway due to PHP macros introducing those.
It appears that current code did not trigger any warnings other than the `unused-parameter` one (which at least confirmed that enabling warnings worked), so nothing in the source needed fixing.
=> Enable strict warnings

ext/otel_observer.c
Fixes failing test case in https://github.com/open-telemetry/opentelemetry-php-instrumentation/pull/135
When post hook handler overrode the return value, it copied the contents of its `zval` to the parameter array passed to next hooks for the same function, so nested hooks would see updated return value.
However, it did not decrement the reference to the old value, plus it created a situation where the new value would be stored in both `ret` and `params[2]`, which both get destroyed separately in the end, making it attempt to free something that's already freed.
Changed it so that 1) `zval_ptr_dtor` is called on old value 2) after new value is moved to `params[2]`, `ret` is set to "undefined" so that destroying it in the end becomes a no-op.
=> Fix leak and double free in post hook return value handling

ext/package.xml, ext/tests/post_hook_returns_cloned_modified_object.phpt
Cloning, then modifying and returning the return value from a post hook can cause either a segfault or a reported memory leak (it seems random, see comment in test).
The use-case for this is changing an immutable object (such as a PSR-7 message) from a post hook.
=> adding failing test for returning cloned modified object from post hook

ext/otel_observer.c
This resolves a warning against gcc10 which was stopping compilation with that compiler. Thanks to @mlocati for identifying the issue and proposing a fix, but this fix proposed by @agoallikmaa seems more portable.
Fixes: https://github.com/open-telemetry/opentelemetry-php/issues/1260
Replaces: https://github.com/open-telemetry/opentelemetry-php-instrumentation/pull/138
=> ensure save_state->opline is initialized

.github/workflows/build.yml, CODEOWNERS, ext/otel_observer.c
- adding macos to github actions
- fix a clang warning that stops compilation on macos
- fixing codeowners to be group-based
Fixes: https://github.com/open-telemetry/opentelemetry-php/issues/1283
=> adding macos build

ext/opentelemetry.c, ext/opentelemetry.stub.php, ext/opentelemetry_arginfo.h, ext/otel_observer.c, ext/tests/with_span/autoloaded_handler.phpt, ext/tests/with_span/handler_not_found.phpt
- fix the namespace so that composer autoloader can find the class, and also add warnings when a handler is not found or could not be loaded
- note that pre handler class param is optional (and not provided for functions)
- add some tests for autoloading and missing handler
=> fixing WithSpanHandler namespace

ext/tests/post_hook_returns_cloned_modified_object.phpt, ext/tests/span_attribute/function_params_non_simple.phpt
Attempting to build for Alpinelinux and have following tests failed
- https://php.watch/rfcs/deprecate-implicitly-nullable-types
- https://github.com/php/php-src/pull/13550
=> fix 2 tests for PHP 8.4

ext/opentelemetry.c, ext/otel_observer.c, ext/php_opentelemetry.h, ext/tests/with_span/disable.phpt
adds a new ini entry, opentelemetry.display_warnings, default=off, to control whether warnings are emitted.
Closes: https://github.com/open-telemetry/opentelemetry-php/issues/1476
=> dont emit warnings by default

ext/config.w32, ext/opentelemetry.c
This patch will allow opentelemetry compiling with php-src statically on Windows.
=> Add windows static build support

.github/workflows/publish-php-debug-images.yml, docker/Dockerfile.alpine, docker/Dockerfile.debian
chore: Updating Dockerfile logic as per https://github.com/open-telemetry/opentelemetry-php-instrumentation/pull/169/files
chore: Updating github action for docker/build-push-action from v3 to v6
=> chore: update build and push action based on dependabot recommendations

.github/workflows/build.yml, .github/workflows/publish-php-debug-images.yml, ext/package.xml, ext/tests/unwind_exit_pcntl_async_signal.phpt, ext/tests/unwind_exit_pcntl_async_signal_leak.phpt
per our support policy, dropping support for PHP 8.0 since it is officially EOL
=> drop php8.0 support
